sudo: required
services:
  - docker

before_install:
  - docker build -t mp4407/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true mp4407/react-test npm test

after_success:
  - docker build -t Mp4407/multi-client -f ./client
  - docker build -t Mp4407/multi-nginx -f ./nginx
  - docker build -t Mp4407/multi-server -f ./server
  - docker build -t Mp4407/multi-worker -f ./worker

  # Login to docker CLI

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Push Images to docker hub
  - docker push Mp4407/multi-client
  - docker push Mp4407/multi-nginx
  - docker push Mp4407/multi-server
  - docker push Mp4407/multi-worker
