sudo: required
services:
  - docker

before_install:
  - docker build -t mp4407/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true mp4407/react-test npm test

after_success:
  - docker build -t mp4407/multi-client ./client
  - docker build -t mp4407/multi-nginx ./nginx
  - docker build -t mp4407/multi-server ./server
  - docker build -t mp4407/multi-worker ./worker

  # Login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Push Images to docker hub
  - docker push mp4407/multi-client
  - docker push mp4407/multi-nginx
  - docker push mp4407/multi-server
  - docker push mp4407/multi-worker
